dubbo:
  application:
    name: boot-pinyougou-shop-web
  registry:
    address: zookeeper://192.168.239.13:2181
server:
  port: 8092

# 不添加数据源启动不起来？
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///pinyougoudb
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 10MB
      enabled: true

# ===================================================================
# 分布式文件系统 FDFS 配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 2000
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.239.13:22122

file:
  file_server.url : http://192.168.239.13/

#单个文件最大尺寸
#spring.servlet.multipart.max-file-size=10mb
#一个请求文件的最大尺寸
#spring.servlet.multipart.max-request-size=50mb
