dubbo:
  application:
    name: boot-pinyougou-content-service
  protocol:
    name: dubbo
    port: 20881
  #  monitor: registry
  registry:
    address: zookeeper://192.168.239.13:2181

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///pinyougoudb
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8082

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # classpath后面写个星*，扫面所有模块
  mapper-locations: classpath*:/mapper/*.xml
