server:
  port: 8093

dubbo:
  application:
    name: boot-pinyougou-portal-web
  registry:
    address: zookeeper://192.168.239.13:2181
#  monitor:
#    protocol: registry


# 不添加数据源启动不起来？
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///pinyougoudb
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 10MB
      enabled: true
  thymeleaf:
    cache: false

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

# ===================================================================
# 分布式文件系统 FDFS 配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 2000
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
  - 192.168.239.13:22122

file:
  file_server.url : http://192.168.239.13/
